server:
  shutdown: graceful
  port: ${DOC_ASSEMBLY_SERVER_PORT:8080}
spring:
  application:
    name: Document Assembly API
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: "optional:configtree:/mnt/secrets/dg-docassembly/"
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5062/o}
        registration:
          oidc:
            client-id: microservicekey-dg-docassembly-api
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

management:
  endpoint:
    health:
      show-details: "always"
      show-components: "always"
      probes:
        enabled: true
  endpoints:
    web:
      base-path: '/'
      exposure:
        include:
         - health
         - info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: false
    diskspace:
      enabled: false
  info:
     build:
       enabled: true # Whether to enable build info.
     defaults:
       enabled: true # Whether to enable default info contributors.
     env:
       enabled: true # Whether to enable environment info.
     git:
       enabled: true # Whether to enable git info.
       mode: simple # Mode to use to expose git information.

info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:dg-docassembly}
    name: ${PACKAGES_NAME:cor}
#    version: ${PACKAGES_VERSION:unknown}

auth:
  idam:
    client:
      baseUrl: ${IDAM_API_BASE_URI:http://localhost:5062}
      dummy-client-secret: "client-secret"
  provider:
    service:
      client:
        baseUrl: ${S2S_BASE_URI:http://localhost:8489}
azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on


idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:8489}
    totp_secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
    microservice: dg_docassembly_api
  s2s-authorised:
    services: ${S2S_NAMES_WHITELIST:sscs,divorce,ccd,em_gw,xui_webapp}

template-management-api:
  base-url: ${DOCMOSIS_TEMPLATES_ENDPOINT:https://docmosis.aat.platform.hmcts.net}
  auth: ${DOCMOSIS_TEMPLATES_ENDPOINT_AUTH:SOMETHING}
  resource: '/templates/'

docmosis:
  accessKey: ${DOCMOSIS_ACCESS_KEY:SOMETHING}
  render.endpoint: ${DOCMOSIS_RENDER_ENDPOINT:https://docmosis.aat.platform.hmcts.net/rs/render}
  convert.endpoint: ${DOCMOSIS_CONVERT_ENDPOINT:https://docmosis.aat.platform.hmcts.net/rs/convert}

document_management:
  base-url: ${DM_STORE_APP_URL:http://localhost:4603}
  docker_url: http://dm-store:8080

endpoint-toggles:
  enable-secure-document-conversion-endpoint: ${ENABLE_SECURE_DOCUMENT_CONVERSION_ENDPOINT:false}
  enable-secure-document-templ-rend-endpoint: ${ENABLE_SECURE_DOCUMENT_TEMPL_REND_ENDPOINT:false}

# Delete when issueOverride variable is no longer used in SecurityConfiguration.class
oidc:
  issuer: ${OIDC_ISSUER_BASE_URI:http://localhost:8080/openam/oauth2/hmcts}

docmosis-conversion:
  multipart:
    covered-ext: ${DOCMOSIS_MULTIPART_WHITELIST_EXT:doc,docx,pptx,ppt,rtf,txt,xlsx,xls}

httpclient:
  call-timeout: ${HTTPCLIENT_CALL_TIMEOUT:30}
  connection-timeout: ${HTTPCLIENT_CONNECTION_TIMEOUT:60}

case_document_am:
  url: ${CDAM_URL:http://localhost:4455}

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dg.docassembly.rest
  pathsToMatch: /**

logging:
  level:
    uk.gov.hmcts.reform.authorisation.filters: DEBUG
    org.springframework.security: DEBUG
