name: dg-docassembly
apiVersion: v2
home: https://github.com/hmcts/dg-docassembly-api
version: 1.1.18
description: HMCTS Document Assembly API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
